from abc import ABC, abstractmethod

class Agent(ABC):
    @property
    @abstractmethod
    def name(self) -> str:
        """
        The name of the agent.
        """
        pass

    @abstractmethod
    def run(self, input_data: dict) -> dict:
        """
        Run the agent with the given input data.
        
        Args:
            input_data (dict): Dictionary containing input parameters for the agent.
            
        Returns:
            dict: The output or result generated by the agent.
        """
        pass
